version: '3.9'

services:
  nestjs:
    build:
        context: ${NESTJS_APP_CONTEXT}
        dockerfile: ${NESTJS_APP_DOCKERFILE}
        args:
          image_version: ${NESTJS_APP_IMAGE_VERSION}
          image_version_prod: ${NESTJS_APP_IMAGE_VERSION_PRODUCTION}
    environment:
      NODE_ENV: ${NESTJS_APP_NODE_ENV}
    image: ${NESTJS_APP_CONTAINER_NAME}:${NESTJS_APP_TAG}
    container_name: ${NESTJS_APP_CONTAINER_NAME}
    command: tail -f /dev/null
    ports:
      - ${NESTJS_APP_LOCAL_PORT}:3000
    volumes:
      - ${NESTJS_APP_LOCAL_DATA}:/home/app/              
    networks:
      - nest-network
      
networks: 
  nest-network:
    driver: bridge